<a href="https://colab.research.google.com/github/mishraoct786/CollectonExample/blob/master/k_nearest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import sklearn
import pandas as pd 
import numpy as np


In [11]:
from sklearn.datasets import load_iris
iris=load_iris()

In [12]:
df=pd.DataFrame(iris['data'])
print(df.head)

<bound method NDFrame.head of        0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]>


In [13]:
print(iris['target_names'])

['setosa' 'versicolor' 'virginica']


In [14]:
print(iris['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [15]:
x=df
y=iris['target']

In [27]:
#spliting data into Trainee and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)

In [29]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [30]:
#prediction and Accuracy 

x_new =np.array([[5,2.9,1,2]])
prediction=knn.predict(x_new)

In [31]:
iris['target_names'][prediction]

array(['setosa'], dtype='<U10')

In [32]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

y_pred=knn.predict(x_test)

cm=confusion_matrix(y_test, y_pred)

print(cm)
print(accuracy_score(y_test,y_pred))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
0.9736842105263158


#Prediction